export const ACTIVITY_TYPES = {
  RFQ_CREATED: "RFQ_CREATED",
  RFQ_UPDATED: "RFQ_UPDATED",
  RFQ_PUBLISHED: "RFQ_PUBLISHED",

  VENDOR_INVITED: "VENDOR_INVITED",

  QUOTATION_SUBMITTED: "QUOTATION_SUBMITTED",
  QUOTATION_UPDATED: "QUOTATION_UPDATED",

  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  APPROVAL_APPROVED: "APPROVAL_APPROVED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED",

  PO_GENERATED: "PO_GENERATED",

  INVOICE_GENERATED: "INVOICE_GENERATED"
};
